spring:
   h2:
      console:
         enabled: true
         path: "/h2"
         
   jpa:
      properties:
         hibernate:
            show_sql: true

      hibernate:
         ddl-auto: none
            
            
   datasource:
      url: jdbc:h2:./mydb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092;USER=sa;PASSWORD=sa;
      username: sa
      password: sa
      

coindesk_url: https://api.coindesk.com/v1/bpi/currentprice.json      